from __future__ import annotations

import logging
import re

logger = logging.getLogger(__name__)

CLASSIFIER_VERSION = "rules-v1"

_CLASSIFIER_VERSION = CLASSIFIER_VERSION

_PRODUCT_ALIASES: dict[str, tuple[str, ...]] = {
    "paypal_checkout": (
        "paypal checkout",
        "paypal-zahlung",
        "paypal bezahlen",
        "paypal checkout-transaktionen",
        "betal med paypal",
        "betaling via paypal",
        "paypal betaling",
        "paypal betal",
        "betal med venmo",
        "betaling med venmo",
        "venmo",
        "pay with paypal",
        "paga con paypal",
        "betalen met paypal",
    ),
    "goods_and_services": (
        "sending and receiving money for goods and services",
        "geld für waren und dienstleistungen senden/empfangen",
        "geld für waren und dienstleistungen",
        "waren und dienstleistungen",
        "goods and services",
        "goods & services",
        "goods or services",
        "varer og tjenesteydelser",
        "varer og tjenester",
        "bienes y servicios",
        "beni e servizi",
        "goederen en diensten",
        "produkter och tjänster",
        "produkter og tjenester",
    ),
    "advanced_card_payments": (
        "advanced credit and debit card payments",
        "erweiterte kredit- und debitkartenzahlungen",
        "zahlungen mit kredit- und debitkarten mit erweiterten funktionen",
        "kredit- und debitkarten mit erweiterten funktionen",
        "advanced card",
        "erweiterte kartenzahlung",
        "kredit- og betalingskort",
        "kredit- og debitkort",
        "kredit- och debitkort",
        "kreditkort",
        "betalingskort",
        "kortbetalinger",
        "avancerede kortbetalinger",
        "credit and debit card",
        "credit/debit card",
        "tarjetas de crédito y débito",
        "tarjeta de crédito y débito",
        "pagos avanzados con tarjeta",
        "pagos con tarjeta de crédito y débito",
        "cartão de crédito e débito",
        "cartão de crédito",
        "paiement par carte bancaire avancé",
        "paiements par carte bancaire avancés",
        "carte bancaire avancée",
        "cartes bancaires avancées",
        "pagamento con carta di credito e debito avanzata",
        "pagamento avanzato con carta",
        "płatność kartą kredytową i debetową",
        "płatność kartą kredytową",
        "płatności kartą kredytową i debetową",
        "avancerade kortbetalningar",
        "creditcard- en debetcardbetalingen",
        "geavanceerde creditcard",
        "online betalen met creditcard",
        "e-terminal",
        "eterminal",
        "solution hébergée",
        "hosted solution",
        "solución alojada",
        "soluzione ospitata",
        "payments advanced",
        "payments pro",
        "virtual terminal",
        "additional risk",
        "risk factors",
        "chargeback protection",
        "fraud protection",
        "failure to implement",
        "express checkout",
        "foreign exchange",
        "fx as a service",
    ),
    "other_commercial": (
        "all other commercial transactions",
        "alle anderen geschäftlichen transaktionen",
        "sonstige gewerbliche transaktionen",
        "other commercial",
        "sonstige geschäftliche",
        "other commercial transactions",
        "commercial transactions",
        "erhvervsbetalinger",
        "erhverv",
        "øvrige erhvervsbetalinger",
        "alle andre erhvervsbetalinger",
        "andre erhvervsbetalinger",
        "forretningsbetalinger",
        "business payments",
        "øvrige forretningsbetalinger",
        "alle anderen",
        "andere commercial",
        "altre transazioni commerciali",
        "otras transacciones comerciales",
        "autres transactions commerciales",
        "andre forretningstransaksjoner",
        "pozostałe transakcje handlowe",
        "campaign",
        "store cash",
        "pyusd",
        "pay by bank",
        "ach",
    ),
    "alternative_payment_methods": (
        "alle anderen alternativen zahlungsmethoden",
        "alternative zahlungsmethode",
        "alternative zahlungsmethoden",
        "alternative payment method",
        "alternative payment methods",
        "all other alternative payment methods",
        "apm-transaktionsgebühren",
        "apm",
        "abm",
        "alternativ betalingsmetode",
        "alternative betalingsmetode",
        "alternative betaalmethode",
        "métodos de pago alternativos",
        "metodi di pagamento alternativi",
        "metodo di pagamento alternativo",
        "online bank transfer",
        "online bankoverførsel",
        "bankoverførsel",
        "bank transfer",
        "cash a check",
        "cheque",
        "check",
    ),
    "guest_checkout": (
        "zahlung eines nutzers unserer bedingungen für zahlungen ohne paypal-konto",
        "zahlungen ohne paypal-konto",
        "payments without a paypal account",
        "zahlung ohne paypal-konto",
        "guest checkout",
        "betalinger uden en paypal-konto",
        "uden en paypal-konto",
        "uden paypal-konto",
        "betal uden paypal",
        "betalning utan paypal-konto",
        "betalning utan paypal",
        "betaling uten paypal-konto",
        "betalen zonder paypal-account",
        "payer sans compte paypal",
        "pagar sin cuenta de paypal",
        "pagamento senza conto paypal",
        "płatność bez konta paypal",
    ),
    "invoice_pay_later": (
        "rechnungskauf mit ratepay",
        "ratepay",
        "invoice payments",
        "pay later",
        "ratenzahlungsangebote",
        "rechnungskauf",
        "faktura",
        "fakturabetaling",
        "fakturabetalning",
        "invoice payment",
    ),
    "qr_code_payments": (
        "qr-code-transaktionen",
        "qr-code transactions",
        "qr-code-zahlungen",
        "qr code transactions",
        "qr-code",
        "qr code",
        "qr-code-betalinger",
        "qr kode betalinger",
        "qr kode-betalinger",
        "qr-code-betaling",
        "qr-kode-betalinger",
        "qr-kode",
        "qr kod",
        "qr-kod",
        "qr kode",
        "codice qr",
        "transazioni con codice qr",
        "código qr",
        "códigos qr",
        "transacciones con códigos qr",
        "transacciones con código qr",
        "kódu qr",
        "kodem qr",
        "pomocí kódu qr",
        "kódom qr",
        "pomocou kódu qr",
        "qr-kooditapahtumat",
        "qr-koodi",
        "qr-kódos",
        "qr-kódos tranzakciók",
    ),
    "donations": (
        "paypal-spendenaktionen",
        "spendenaktionen",
        "spende",
        "donation",
        "donationer",
        "donations",
        "charity donation",
        "don de",
        "donazioni",
    ),
    "nonprofit": (
        "gemeinnützige organisationen",
        "gemeinnützig",
        "gemeinnutzig",
        "nonprofit organisation",
        "nonprofit",
        "non-profit",
        "velgørende",
        "velgørende organisationer",
        "non-profit organisation",
        "organizaciones sin fines de lucro",
        "organizzazioni senza scopo di lucro",
        "organisasjoner",
        "organizacja non-profit",
        "charitativní transakce",
        "charitativních transakcí",
    ),
    "micropayments": (
        "mikrozahlung",
        "micropayment",
        "kleinbetragszahlung",
        "mikrobetaling",
        "mikrobetalinger",
        "mikromaksu",
        "mikropłatność",
        "micropagos",
        "micropaiement",
    ),
    "chargebacks": (
        "rückbuchungsgebühren",
        "rückbuchung",
        "rückabwicklung",
        "chargeback",
    ),
    "disputes": (
        "konfliktgebühren",
        "konfliktgebühr",
        "streitfall",
        "dispute",
    ),
    "refunds": (
        "rückerstattung",
        "rückzahlung",
        "refund",
    ),
    "currency_conversion": (
        "währungsumrechnung",
        "umrechnung",
        "currency conversion",
        "wechselkurs",
    ),
    "withdrawals": (
        "guthaben von einem paypal-geschäftskonto abbuchen",
        "abbuchen",
        "auszahlung",
        "withdrawal",
        "payout",
        "business debit card",
        "business debit",
        "bargeldabhebung",
        "bargeldabbuchung",
        "atm withdrawal",
        "geldautomat",
        "de business debit card",
        "bank account",
        "to a bank account",
        "withdraw to a bank account",
    ),
    "card_verification": (
        "kartenverifizierung",
        "karten verifizierung",
        "card verification",
        "kartenbestätigung",
    ),
    "sepa_direct_debit": (
        "sepa-lastschrift",
        "sepa lastschrift",
        "sepa direct debit",
        "sepa-elv",
        "lastschrift",
        "domiciliación bancaria",
        "addebito diretto",
        "débit direct sepa",
    ),
    "fraud_protection": (
        "professionelles tool zum betrugsschutz",
        "fraud protection advanced",
        "fraud protection",
        "betrugsschutz",
        "outil de protection contre la fraude",
        "protección antifraude",
        "protezione antifrode",
    ),
    "records_request": (
        "anforderung von unterlagen",
        "records request",
        "document request",
        "document fee",
        "dokumentengebühr",
        "demande de documents",
        "solicitud de documentación",
        "richiesta di documenti",
    ),
    "pay_later_consumer": (
        "paypal-ratenzahlungsangebote",
        "ratenzahlungsangebote",
        "pay in 4",
        "pay later",
        "betal senere",
        "afbetaling",
        "paypal pay later",
        "paypal pay later-tilbud",
        "pay later-tilbud",
        "klarna",
        "afterpay",
    ),
    "pos_transactions": (
        "point of sale",
        "paypal point of sale",
        "präsenter karte",
        "card present",
        "kortforevisning",
        "kortterminal",
        "kortterminaler",
        "kortpresent",
    ),
}

_PRODUCT_ORDER = list(_PRODUCT_ALIASES)

_TABLE_CATEGORY_KEYWORDS: dict[str, tuple[str, ...]] = {
    "commercial_rate_table": (
        "standardgebühr beim empfang von inlandstransaktionen",
        "empfangen von inlandstransaktionen",
        "standard transaction fees",
        "commercial transaction fees",
        "geschäftlichen transaktionen",
        "commercial transactions",
        "standardgebyr",
        "standardavgift",
        "standaardtarief",
        "tarifa estándar",
        "tarifa standard",
        "tarifa padrão",
        "tariffa standard",
        "tarification standard",
        "standard taxa",
        "standardtaxa",
        "standardsats",
        "standardowa stawka",
        "standardní sazba",
        "štandardná sadzba",
        "szokásos díja",
        "standard fee",
        "standard rate",
        "modtagelse af indenlandske betalinger",
        "innenlands",
        "indland",
        "innenlandske",
        "inhemska",
        "binnenland",
        "binnenlandse",
        "nationales",
        "transacciones nacionales",
        "nazionali",
        "nacionais",
        "nationella",
        "krajowych",
        "krajinskih",
        "vnitrostátních",
        "domácich",
        "belföldi",
        "εσωτερικές",
        "naționale",
        "национални",
        "nacionalnih",
        "kotimaisten",
        "domestic payments",
        "domestic",
        "commerciële",
        "commerciale",
        "commerciales",
        "kommersielle",
        "kommercielle",
        "kommersiella",
        "kommercielle",
        "kommersielle",
        "komercyjne",
        "komerčních",
        "komerčných",
        "kereskedelmi",
        "εμπορικές",
        "comerciale",
        "comercial",
        "comerciale",
        "tranzakcje",
        "transakcji",
        "transakcí",
        "transakcií",
        "transakció",
        "transakcije",
        "receiving domestic",
        "recepción de transacciones nacionales",
        "recebimento de transações nacionais",
        "ricezione di transazioni nazionali",
        "recepción de transacciones nacionales",
        "ricezione di pagamenti",
    ),
    "online_card_rate_table": (
        "paypal-dienste für online-kartenzahlungen",
        "paypal-dienste für online-zahlungen",
        "online card payments",
        "online-kartenzahlungen",
        "online card",
        "online-kortbetaling",
        "online kort",
        "online kortbetalingstjenester",
        "online-kort",
        "kortbetalingstjenester",
        "kortbetalningstjänster",
        "kortbetalning",
        "kortfinansierad",
        "online kártyás",
        "online kart",
        "online karta",
        "online kortti",
        "online kort",
        "online kartę",
        "online kort",
        "online kart",
        "online kart",
        "online card payment services",
        "online payment services",
        "servizi paypal di pagamento online con carta",
        "servizi di pagamento online con carta",
        "pagamento online con carta",
        "online kartično",
        "online kartica",
        "servizi di pagamento con carta",
        "services de paiement par carte",
        "services de paiement en ligne",
        "service de paiement en ligne",
        "paiement en ligne",
        "serviços de pagamento com cartão",
        "serviços de pagamento online",
        "servicios de pago con tarjeta",
        "servicios de pago en línea",
        "serviços de pagamento online",
        "tarjetas de crédito y débito",
        "kredit- och debitkort",
        "credit and debit card",
        "kredit- og betalingskort",
        "kredit- och betalkort",
        "avancerat kredit- och betalkort",
        "advanced credit and debit card",
        "online-betalningstjänster",
        "online betalingstjenester",
        "online betalingsløsninger",
        "online betalingstjenester",
        "online betaling",
        "online maksut",
        "online maksu",
        "online platby",
        "online platba",
        "služeb paypal pro online platby",
        "služieb paypal pre platby online",
        "online betaalservices van paypal",
        "transacties ontvangen via online betaalservices",
        "pago por internet de paypal",
        "servicios de pago por internet",
        "płatności online kartą w systemie paypal",
        "usług płatności online kartą",
        "online πληρωμές",
        "online πληρωμων",
        "ηλεκτρονικές πληρωμές",
        "ηλεκτρονικες πληρωμες",
        "υπηρεσιών paypal για ηλεκτρονικές",
        "υπηρεσιων paypal για ηλεκτρονικες",
        "ηλεκτρονικές υπηρεσίες",
        "ηλεκτρονικες υπηρεσιες",
    ),
    "goods_and_services_rate_table": (
        "geld für waren und dienstleistungen",
        "goods and services",
    ),
    "donation_rate_table": (
        "empfang von inlandsspenden",
        "donation",
        "spenden",
        "donationer",
        "donationer",
        "donations",
        "donaties",
        "donativos",
        "donativas",
        "doações",
        "donazioni",
        "donationer",
        "donationer",
        "lahjoitukset",
        "darowizn",
        "darowizn krajowych",
        "odbiór darowizn",
        "príspevkov",
        "príspevky",
        "domácich príspevkov",
        "binnenlandse donaties",
        "ontvangen van binnenlandse donaties",
        "adományok",
        "δωρεές",
        "δωρεες",
        "δωρεών",
        "δωρεων",
        "donatii",
        "дарения",
        "donacije",
        "donacijo",
        "donationer",
        "donaties",
        "příspěvky",
        "příspěvků",
        "receiving domestic donations",
        "recepción de donativos nacionales",
        "recebimento de doações domésticas",
        "ricezione di donazioni nazionali",
        "λήψη εγχώριων δωρεών",
        "ληψη εγχωριων δωρεων",
        "sending international donations",
        "receiving international donations",
        "skicka internationella donationer",
        "ta emot internationella donationer",
        "enviar donaciones internacionales",
        "recibir donaciones internacionales",
        "envoyer des dons internationaux",
        "recevoir des dons internationaux",
        "invio di donazioni internazionali",
        "ricezione di donazioni internazionali",
        "wysyłanie międzynarodowych darowizn",
        "odbieranie międzynarodowych darowizn",
        "αποστολή διεθνών δωρεών",
        "λήψη διεθνών δωρεών",
        "senden von internationalen spenden",
        "empfangen von internationalen spenden",
        "lähettää kansainvälisiä lahjoituksia",
        "vastaanottaa kansainvälisiä lahjoituksia",
    ),
    "nonprofit_rate_table": (
        "gemeinnützige organisationen",
        "nonprofit",
        "non-profit",
        "velgørende",
        "velgørende organisationer",
        "non-profit organisation",
        "organizaciones sin fines de lucro",
        "organizaciones benéficas",
        "organizzazioni senza scopo di lucro",
        "enti benefici",
        "organisasjoner",
        "organizacja non-profit",
        "organizacje charytatywne",
        "charitatívnych",
        "charitativních",
        "charitativní transakce",
        "charitativních transakcí",
        "vnitrostátních charitativních transakcí",
        "charitatívnymi príspevkami",
        "domácich transakcií spojených s charitatívnymi príspevkami",
        "jótékonysági",
        "jótékonysági",
        "välgörenhetsorganisationer",
        "välgörenhet",
        "φιλανθρωπικές",
        "φιλανθρωπικά",
        "φιλανθρωπικού",
        "φιλανθρωπικου",
        "instituições de solidariedade",
        "instituição de caridade",
        "institución de solidaridad",
        "entidades sin ánimo de lucro",
        "associazioni di volontariato",
        "caritative",
        "caritat",
        "caridad",
        "caridade",
        "nonguvernamental",
        "humanitar",
        "charity",
        "charitable",
        "liefdadigheid",
        "liefdadigheids",
        "receiving domestic charity",
        "receiving charity",
        "carity transactions",
        "associations caritatives",
    ),
    "apm_rate_table": (
        "alternative zahlungsmethode",
        "alternative payment method",
        "apm-transaktionen",
        "apm",
        "alternativ betalingsmetode",
        "alternative betalingsmetode",
        "alternative betaalmethode",
        "métodos de pago alternativos",
        "metodi di pagamento alternativi",
        "metodo di pagamento alternativo",
        "andere betaalmethode",
        "autre moyen de paiement",
        "autre moyen",
        "autre mode de paiement",
        "alternatív fizetési",
        "alternatívny spôsob platby",
        "alternativní způsob platby",
        "alternatywna forma płatności",
        "alternatywne metody płatności",
        "alternativ betalningsmetod",
        "alternativ betalingsmåte",
        "vaihtoehtoinen maksutapa",
        "vaihtoehtoinen",
        "vmt",
        "apm-transaksjoner",
        "apm-transakcje",
        "apm-transakcje",
        "apm-transakcí",
        "apm-transakcí",
        "apm-transakciók",
        "apm-transakcije",
        "apm-transakcije",
        "alternative betalingsmetoder",
        "alternative payment methods",
        "alternative payment",
    ),
    "pos_rate_table": (
        "point of sale",
        "paypal point of sale",
        "point de vente",
        "points de vente",
        "präsenter karte",
        "kortforevisning",
        "card present",
        "point-of-sale",
        "ponto de venda",
        "punto de venta",
        "punto vendita",
        "punkty sprzedaży",
        "płatności kartą",
        "kassapääte",
        "kassapääte",
        "platební terminál",
        "platební terminály",
        "terminál",
        "kortterminal",
        "kortterminaler",
        "kortläsare",
        "pos-terminal",
        "pos terminal",
        "paypal pos",
        "pos-betalinger",
        "pos transakcije",
        "pos transakcie",
        "pos-transakcije",
        "kassasystem",
        "korttransaktioner",
        "korttransaktion",
        "presentkort",
        "transazioni tramite pos di paypal",
        "transazioni tramite pos",
        "transactions via paypal pos",
        "pos di paypal",
        "tramite pos",
        "via paypal pos",
    ),
    "micropayment_rate_table": (
        "mikrozahlung",
        "micropayment",
        "mikrobetaling",
        "mikrobetalinger",
        "mikromaksu",
        "mikromaksujen",
        "mikrobetaling",
        "mikrobetalinger",
        "mikrobetaling",
        "mikrobetalingar",
        "mikropłatność",
        "mikropłatności",
        "mikrotransakcí",
        "mikrotransakcií",
        "mikrotransakciók",
        "mikrotransakcije",
        "mikrotransakcije",
        "micropagos",
        "micropagos",
        "micropaiement",
        "micropaiements",
        "micropagamentos",
        "mikrobetalning",
        "mikrobetalningar",
        "mikromaksu",
        "μικροπληρωμές",
        "μικροπληρωμες",
        "μικροπληρωμών",
        "μικροπληρωμων",
        "mikroplatby",
        "mikroplatby",
    ),
    "fixed_fee_table": (
        "festgebühr",
        "fixed fee",
        "fast gebyr",
        "fast avgift",
        "tarifa fija",
        "comisión fija",
        "comissão fixa",
        "taxa fixa",
        "vast bedrag",
        "vaste kosten",
        "tariffa fissa",
        "paušální poplatek",
        "opłata stała",
        "frais fixe",
        "commission fixe",
        "kiinteä palkkio",
        "kiinteä maksu",
        "fixný poplatok",
        "fiksna naknada",
        "fiksna provizija",
        "comision fixa",
        "σταθερή χρέωση",
        "ค่าธรรมเนียมคงที่",
        "อัตราคงที่",
        "rögzített díja",
        "rögzített díj",
        "固定費用",
    ),
    "international_surcharge_table": (
        "zusätzliche prozentuale gebühr",
        "prozentuale zusatzgebühr",
        "international surcharge",
        "additional percentage fee",
        "additional percentage-based fee",
        "additional percentage based fee",
        "additional percentage",
        "international payments",
        "internationales",
        "internationella",
        "internationale",
        "internasjonale",
        "kansainvälisten",
        "kansainvälis",
        "medzinárodné",
        "medzinárodné",
        "mezinárodní",
        "zahraniční",
        "nemzetközi",
        "διεθνείς",
        "internaționale",
        "международни",
        "međunarodne",
        "mednarodne",
        "ausland",
        "zusatzgebühr",
        "additional service",
        "service fee",
        "servicegebühr",
        "servicegebyr",
        "serviceavgift",
        "extra percentage",
        "ekstra procentbaseret gebyr",
        "yderligere procentdel af gebyr",
        "extra procentuell avgift",
        "extra procentbaserad avgift",
        "lisäprosenttimaksu",
        "prosenttiperusteinen lisäpalkkio",
        "supplément de commission",
        "sobretasa internacional",
        "tarifa adicional porcentual",
        "tarifa adicional baseada em porcentagem",
        "comissão percentual adicional",
        "tariffa percentuale aggiuntiva",
        "op een percentage gebaseerde",
        "dodatkowa opłata procentowa",
        "dodatečný procentní poplatek",
        "dodatočný percentuálny poplatok",
        "százalékos kiegészítő díja",
        "dodatni postotak",
        "dodatni odstotek",
        "πρόσθετη χρέωση βάσει ποσοστού",
        "προσθετη χρεωση βασει ποσοστου",
        "πρόσθετη χρέωση υπηρεσίας",
        "προσθετη χρεωση υπηρεσιας",
        "διεθνών",
        "διεθνων",
        "διεθνείς",
        "διεθνεις",
        "λήψη διεθνών",
        "ληψη διεθνων",
        "dodatna naknada",
        "dodatna pristojbina",
    ),
    "currency_conversion_table": (
        "währungsumrechnung",
        "umrechnung",
        "currency conversion",
        "guthaben umrechnen",
        "valuutan muuntaminen",
        "valuutanvaihto",
        "valuuttakurssit",
        "valutaomregning",
        "valuuttakurssi",
        "wisselkoers",
        "cambio",
        "cambio de divisa",
        "cambio valuta",
        "conversione",
        "conversão",
        "cambio",
        "devizni",
        "valut",
        "valuuta",
        "valuta",
        "převod",
        "převodu měny",
        "převod zůstatku na firemním účtu",
        "prevod",
        "prevod meny",
        "konverzia",
        "konverzija",
        "μετατροπή",
        "conversie",
        "conversion",
        "valutaveksling",
        "valutakurs",
        "valutakurser",
        "valutakurser",
        "kryptoměna",
        "kryptomena",
        "criptomoeda",
        "criptomoneda",
        "kryptovaluta",
        "converting balance",
        "converting",
    ),
    "other_fees_table": (
        "sonstige gebühren",
        "other fees",
        "autres frais",
        "altre commissioni",
        "otros honorarios",
        "otros cargos",
        "outras taxas",
        "overige kosten",
        "sonstige kosten",
        "overige vergoedingen",
        "diversas taxas",
        "andere kosten",
        "muut kulut",
        "muut maksut",
        "muut kulud",
        "pozostałe opłaty",
        "ostatní poplatky",
        "iné poplatky",
        "ostali troškovi",
        "druge naknade",
        "altres comissions",
        "altres despeses",
        "diger ucretler",
        "diger ücretler",
        "diversi",
        "diverse",
        "miscellaneous fees",
        "additional fees",
    ),
}

_TABLE_NEGATIVE_SIGNALS: dict[str, tuple[str, ...]] = {
    "commercial_rate_table": (
        "spende",
        "donation",
        "donativos",
        "donativas",
        "donaciones",
        "donazione",
        "donazioni",
        "doações",
        "gemeinnützig",
        "nonprofit",
        "non-profit",
        "organizaciones benéficas",
        "organizaciones sin fines de lucro",
        "organizacion benéfica",
        "organizzazioni senza scopo di lucro",
        "organizzazione senza scopo di lucro",
        "enti benefici",
        "ente benefico",
        "organizações beneficentes",
        "organização beneficente",
        "sem fins lucrativos",
        "mikrozahlung",
        "micropayment",
        "alternative zahlungsmethode",
        "alternative payment",
        "online-kartenzahlungen",
        "online card",
        "point of sale",
        "qr-code",
        "qr code",
        "sonstige gebühren",
        "rückbuchung",
        "chargeback",
    ),
    "online_card_rate_table": (
        "sonstige gebühren",
        "rückbuchung",
        "chargeback",
        "betrugsschutz",
        "professionelles tool",
        "professional tool",
    ),
}

_TABLE_CATEGORY_SCHEDULE: dict[str, str] = {
    "commercial_rate_table": "commercial",
    "online_card_rate_table": "online_card_payments",
    "goods_and_services_rate_table": "goods_and_services",
    "donation_rate_table": "donations",
    "nonprofit_rate_table": "nonprofit",
    "apm_rate_table": "alternative_payment_methods",
    "pos_rate_table": "pos_transactions",
    "micropayment_rate_table": "micropayments",
}

_CANONICAL_AMOUNT_RE = re.compile(r"[+-]?(?:\d{1,3}(?:[.,]\d{3})+(?:[.,]\d+)?|\d+(?:[.,]\d+)?)")

_PERCENTAGE_RE = re.compile(r"([0-9]+(?:[.,][0-9]+)?)\s*%")

_PLUS_FIXED_RE = re.compile(r"[+]\s*(.+)")

_DIRECT_FIXED_FEE_PRODUCTS: frozenset[str] = frozenset(
    {
        "sepa_direct_debit",
        "fraud_protection",
        "records_request",
        "card_verification",
        "withdrawals",
    }
)

_CATEGORY_SPECIFIC_TABLES: frozenset[str] = frozenset(
    {
        "nonprofit_rate_table",
        "donation_rate_table",
        "micropayment_rate_table",
        "pos_rate_table",
        "goods_and_services_rate_table",
        "withdrawals_rate_table",
    }
)

_DEFAULT_CURRENCY_BY_MARKET: dict[str, str] = {
    "DE": "EUR",
    "AT": "EUR",
    "BE": "EUR",
    "NL": "EUR",
    "FR": "EUR",
    "ES": "EUR",
    "IT": "EUR",
    "PT": "EUR",
    "IE": "EUR",
    "GR": "EUR",
    "FI": "EUR",
    "LU": "EUR",
    "CY": "EUR",
    "MT": "EUR",
    "SK": "EUR",
    "SI": "EUR",
    "EE": "EUR",
    "LV": "EUR",
    "LT": "EUR",
    "GB": "GBP",
    "US": "USD",
    "CA": "CAD",
    "AU": "AUD",
    "JP": "JPY",
    "CH": "CHF",
    "IN": "INR",
    "BR": "BRL",
    "MX": "MXN",
    "SG": "SGD",
    "HK": "HKD",
    "NZ": "NZD",
    "SE": "SEK",
    "NO": "NOK",
    "DK": "DKK",
    "PL": "PLN",
    "CZ": "CZK",
    "HU": "HUF",
    "IL": "ILS",
    "ZA": "ZAR",
    "AE": "AED",
}

_FEE_HEADER_KEYWORDS: frozenset[str] = frozenset(
    {"fee", "gebühr", "charge", "cost", "price", "preis", "betrag", "amount", "tarif", "rate"}
)

_NON_FEE_HEADER_KEYWORDS: frozenset[str] = frozenset(
    {
        "code",
        "vorwahl",
        "prefix",
        "country",
        "market",
        "region",
        "number",
        "no.",
        "phone",
        "telephone",
        "int.",
        "international",
        "markt",
        "land",
    }
)

_PRODUCT_CATEGORY_MAP: dict[str, str] = {
    "alternative_payment_methods": "apm_rate_table",
    "advanced_card_payments": "online_card_rate_table",
    "pos_transactions": "pos_rate_table",
    "micropayments": "micropayment_rate_table",
    "donations": "donation_rate_table",
    "nonprofit": "nonprofit_rate_table",
    "goods_and_services": "goods_and_services_rate_table",
    "paypal_checkout": "commercial_rate_table",
    "other_commercial": "commercial_rate_table",
    "guest_checkout": "commercial_rate_table",
    "invoice_pay_later": "commercial_rate_table",
    "pay_later_consumer": "commercial_rate_table",
    "qr_code_payments": "commercial_rate_table",
    "chargebacks": "online_card_rate_table",
    "refunds": "online_card_rate_table",
    "disputes": "online_card_rate_table",
    "card_verification": "apm_rate_table",
    "currency_conversion": "currency_conversion_table",
    "withdrawals": "apm_rate_table",
}

_TABLE_CATEGORY_PRODUCT: dict[str, str] = {
    "nonprofit_rate_table": "nonprofit",
    "donation_rate_table": "donations",
    "micropayment_rate_table": "micropayments",
    "apm_rate_table": "alternative_payment_methods",
    "pos_rate_table": "pos_transactions",
    "online_card_rate_table": "advanced_card_payments",
    "goods_and_services_rate_table": "goods_and_services",
    "commercial_rate_table": "other_commercial",
    "withdrawals_rate_table": "withdrawals",
}

_FIXED_FEE_KEYWORDS = (
    "festgebühr",
    "fixed fee",
    "fast gebyr",
    "fast avgift",
    "tarifa fija",
    "comisión fija",
    "comissão fixa",
    "tarifa fixa",
    "taxa fixa",
    "vast bedrag",
    "vaste kosten",
    "tariffa fissa",
    "paušální poplatek",
    "pevný poplatek",
    "opłata stała",
    "frais fixe",
    "commission fixe",
    "kiinteä palkkio",
    "kiinteä maksu",
    "fixný poplatok",
    "pevný poplatok",
    "fiksna naknada",
    "fiksna provizija",
    "comision fixa",
    "σταθερή χρέωση",
    "ค่าธรรมเนียมคงที่",
    "อัตราคงที่",
    "rögzített díja",
    "rögzített díj",
    "fix díj",
    "固定費用",
)

_MIN_MAX_FEE_KEYWORDS = (
    "mindest",
    "höchst",
    "minimum",
    "maximum",
    "minim",
    "maxim",
    "mínim",
    "máxim",
    "massim",
    "minsta",
    "största",
    "minste",
    "maks",
    "lavest",
    "højest",
    "obergrenze",
    "obergr",
    "limit",
    "cap",
    "ceiling",
    "floor",
    "payout maximum",
    "withdrawal limit",
    "transaction limit",
    "send limit",
    "receive limit",
    "mindestbetrag",
    "höchstbetrag",
    "max cap",
    "max limit",
    "maximum cap",
)

_DIRECT_FIXED_FEE_KEYWORDS = (
    "chargeback",
    "rückbuchung",
    "rückbuchungs",
    "dispute",
    "streit",
    "claim",
    "withdrawal",
    "auszahlung",
    "auszahlungen",
    "payout",
    "verification",
    "verifizierung",
    "authorization",
    "autorisierung",
    "refund",
    "rückerstattung",
    "rückerstattungen",
    "erstattung",
    "terugbetaling",
)

_INTERNATIONAL_SURCHARGE_KEYWORDS = (
    "prozentuale zusatzgebühr",
    "zusätzliche prozentuale gebühr",
    "international surcharge",
    "receiving international transactions",
    "sending international transactions",
    "additional percentage fee",
    "additional percentage-based fee",
    "additional percentage based fee",
    "additional percentage",
    "international payments",
    "ekstra procentbaseret gebyr",
    "yderligere procentdel af gebyr",
    "extra procentuell avgift",
    "extra procentbaserad avgift",
    "lisäprosenttimaksu",
    "prosenttiperusteinen lisäpalkkio",
    "supplément de commission",
    "sobretasa internacional",
    "extra percentage",
    "service fee",
    "servicegebühr",
    "servicegebyr",
    "serviceavgift",
    "service charge",
    "servicekosten",
    "servicekostnad",
    "servicekostnader",
    "yderligere servicegebyr",
    "ytterligare serviceavgift",
    "tarifa de servicio adicional",
    "comissão de serviço adicional",
    "tariffa di servizio aggiuntiva",
    "frais de service supplémentaires",
    "dodatkowa opłata za usługę",
    "dodatečný poplatek za služby",
    "dodatočný poplatok za služby",
    "πρόσθετη χρέωση υπηρεσίας",
    "további szolgáltatási díj",
    "tarifa adicional porcentual",
    "comisión porcentual adicional",
    "comisión adicional con base en un porcentaje",
    "tarifa adicional baseada em porcentagem",
    "comissão percentual adicional",
    "tariffa percentuale aggiuntiva",
    "op een percentage gebaseerde",
    "dodatkowa opłata procentowa",
    "dodatečný procentní poplatek",
    "dodatočný percentuálny poplatok",
    "százalékos kiegészítő díja",
    "dodatni postotak",
    "dodatni odstotek",
    "πρόσθετη χρέωση βάσει ποσοστού",
    "additional service",
    "additional service fee",
)

_LIMIT_OR_CAP_KEYWORDS = (
    "withdrawal limit",
    "withdrawal limits",
    "payout limit",
    "payout limits",
    "payout maximum",
    "payout maximums",
    "payout max",
    "payout minimum",
    "payout min",
    "transaction limit",
    "transaction limits",
    "send limit",
    "send limits",
    "receive limit",
    "receive limits",
    "mindest",
    "höchst",
    "minimum",
    "maximum",
    "minim",
    "maxim",
    "mínim",
    "máxim",
    "massim",
    "minsta",
    "största",
    "minste",
    "maks",
    "lavest",
    "højest",
    "obergrenze",
    "obergr",
    "untergrenze",
    "untergr",
    "limit",
    "limit cap",
    "cap",
    "ceiling",
    "floor",
    "max cap",
    "max limit",
    "maximum cap",
    "min cap",
    "minimum cap",
    "mindestbetrag",
    "höchstbetrag",
    "no more than",
    "not more than",
    "not less than",
    "at least",
    "at most",
    "up to",
    "up-to",
)

_APM_METHOD_ALIASES: dict[str, tuple[str, ...]] = {
    "thai_online_bank_transfer": (
        "thai online bank transfer",
        "thailändsk online bank transfer",
        "thailandsk online bankoverførsel",
        "thailändische online banküberweisung",
        "thailändische online-banküberweisung",
        "thailändische online bank überweisung",
        "thai online bank",
        "thai online bankoverførsel",
        "thai online banküberweisung",
        "thai online bankoverschrijving",
        "thai online bankovní převod",
        "thai online bankový prevod",
        "thai online banki átutalás",
        "thai virement bancaire en ligne",
        "thai bonifico bancario online",
        "thai transferencia bancaria online",
        "thai transferência bancária online",
        "thai verkkopankkisiirto",
        "thailändsk",
        "thailandsk",
        "thaimaan",
        "thaimaa",
        "thaiföldi",
        "thaïlandaise",
        "tailandesa",
        "tailandese",
        "tailandés",
        "tajlandzkiej",
        "thajsku",
        "thajska",
        "thajském",
        "thajskom",
        "thai",
    ),
    "latvian_online_bank_transfer": (
        "latvian online bank transfer",
        "lettisk online bank transfer",
        "latvijas online bank transfer",
        "latvian online bankoverførsel",
        "lettische online banküberweisung",
        "lettische online-banküberweisung",
        "lettische online bank überweisung",
        "latvian online bank",
        "latvian online banküberweisung",
        "latvian online bankoverschrijving",
        "latvian online bankovní převod",
        "latvian online bankový prevod",
        "latvian online banki átutalás",
        "latvian virement bancaire en ligne",
        "latvian bonifico bancario online",
        "latvian transferencia bancaria online",
        "latvian transferência bancária online",
        "latvian verkkopankkisiirto",
        "lettisk",
        "lettische",
        "latvijas",
        "latvijska",
        "läti",
        "lettországi",
        "letonska",
        "letonské",
        "letonskom",
        "latvian",
    ),
    "lithuanian_online_bank_transfer": (
        "lithuanian online bank transfer",
        "litauisk online bank transfer",
        "lietuvos online bank transfer",
        "lithuanian online bankoverførsel",
        "litauische online banküberweisung",
        "litauische online-banküberweisung",
        "litauische online bank überweisung",
        "lithuanian online bank",
        "lithuanian online banküberweisung",
        "lithuanian online bankoverschrijving",
        "lithuanian online bankovní převod",
        "lithuanian online bankový prevod",
        "lithuanian online banki átutalás",
        "lithuanian virement bancaire en ligne",
        "lithuanian bonifico bancario online",
        "lithuanian transferencia bancaria online",
        "lithuanian transferência bancária online",
        "lithuanian verkkopankkisiirto",
        "litauisk",
        "litauische",
        "lie tuvos",
        "liettualainen",
        "lietuvos",
        "litván",
        "litewska",
        "litewskim",
        "lithuanian",
    ),
    "estonian_online_bank_transfer": (
        "estonian online bank transfer",
        "estonian online bank",
        "estonia online bank transfer",
        "estonia online bank",
        "estonia banks",
        "estonian banks",
        "estonian bank transfer",
        "estnische online banküberweisung",
        "estnische online bank",
        "online bankovní převod v estonsku",
        "online bankový prevod v estónsku",
        "online banki átutalás észtország",
        "virement bancaire en ligne estonien",
        "bonifico bancario online estone",
        "transferencia bancaria online de estonia",
        "transferência bancária online da estónia",
        "estnisk",
        "estnische",
        "esti",
        "estonia",
        "estonian",
        "estonsku",
        "estónsku",
        "estnischen",
    ),
    "online_bank_transfer": (
        "online bank transfer",
        "online bankoverførsel",
        "online banküberweisung",
        "online-banküberweisung",
        "online bank überweisung",
        "online bankoverschrijving",
        "online bankovní převod",
        "online bankový prevod",
        "online banki átutalás",
        "virement bancaire en ligne",
        "bonifico bancario online",
        "transferencia bancaria online",
        "transferência bancária online",
        "verkkopankkisiirto",
        "bank transfer",
        "banktransfer",
        "online bank",
        "banküberweisung",
        "bankoverschrijving",
        "banköverföring",
        "bankoverførsel",
    ),
    "skrill": ("skrill",),
    "ovo_premium": (
        "ovo premium",
        "ovo",
    ),
    "gopay": (
        "gopay",
        "go pay",
    ),
    "blik_pay_later": (
        "blik pay later",
        "blik",
    ),
    "kredivo": ("kredivo",),
    "floa_pay": (
        "floa pay",
        "floa",
    ),
    "scalapay": ("scalapay",),
    "naver_pay": (
        "naver pay",
        "naverpay",
    ),
    "picpay": ("picpay",),
    "nupay": ("nupay",),
    "true_money": (
        "true money",
        "truemoney",
    ),
    "airtel": ("airtel",),
    "pago_efectivo": (
        "pago efectivo",
        "pagoefectivo",
    ),
    "mercado_pago": (
        "mercado pago",
        "mercadopago",
    ),
    "pesa": (
        "pesa",
        "m-pesa",
        "mpesa",
    ),
    "shopee_pay": (
        "shopee pay",
        "shopeepay",
    ),
}

_APM_SPECIAL_METHOD_IDS: frozenset[str] = frozenset(
    [
        "thai_online_bank_transfer",
        "latvian_online_bank_transfer",
        "lithuanian_online_bank_transfer",
        "estonian_online_bank_transfer",
        "online_bank_transfer",
        "skrill",
        "ovo_premium",
        "gopay",
        "blik_pay_later",
        "kredivo",
        "floa_pay",
        "scalapay",
        "naver_pay",
        "picpay",
        "nupay",
        "true_money",
        "airtel",
        "pago_efectivo",
        "mercado_pago",
        "pesa",
        "shopee_pay",
        "twint",
        "doku_wallet",
        "linkaja",
        "jenius_pay",
        "paysera",
        "dragonpay",
        "codi",
        "halopesa",
        "mixx_by_yas",
        "payattitude",
        "pesalink",
        "promptpay_qr",
        "pse",
        "bre_b",
        "nibss_bank_transfer",
        "nequi",
        "vietqr",
        "coins",
        "paysafecard",
        "oxxopay",
        "klarna",
        "fiuu_cash",
        "opay",
        "apple_pay",
        "wire_transfer",
        "spei",
        "swish",
        "dimo",
    ]
)

_APM_SORTED_ALIASES: list[tuple[str, str]] = sorted(
    [(canonical, alias) for canonical, aliases in _APM_METHOD_ALIASES.items() for alias in aliases],
    key=lambda item: (-len(item[1]), item[0], item[1]),
)

_APM_SEPARATOR_RE = re.compile(
    r"[,;/]|"
    r"(?:\s+(?:and|und|i|y|et|og|ja|oraz|och|e)\s+)",
    re.IGNORECASE,
)

_APM_PUNCTUATION_RE = re.compile(r"[^\w\s]")

_APM_EXAMPLE_PHRASE_RE = re.compile(r"\b(z\s*\.\s*b\s*\.?|e\s*\.\s*g\s*\.?|np\.|ex\.?)\b")

_APM_HEADER_PHRASES: set[str] = {
    "alle anderen alternativen zahlungsmethoden",
    "alle anderen alternativen zahlungsmethode",
    "alternative zahlungsmethode",
    "alternative zahlungsmethoden",
    "alternative payment method",
    "alternative payment methods",
    "alternative payment methods (apms) through pay links and buttons",
    "all other alternative payment methods",
    "all other alternative payment method",
    "all other apm",
    "standard credit and debit card payments",
    "credit and debit card payments",
    "other third-party wallets",
    "third-party wallets",
    "third party digital wallet",
    "third-party digital wallet",
    "autres moyens de paiement alternatifs",
    "autres moyens de paiement",
    "altre modalità di pagamento alternative",
    "otros métodos de pago alternativos",
    "otras carteras externas",
    "u otras carteras externas",
    "andere betaalmethode",
    "andere betaalmethoden",
    "andere alternatieve betaalmethoden",
    "andere alternative betalingsmetoder",
    "andere alternative zahlungsmethoden",
    "andere alternative zahlungsmethode",
    "andre alternative betalingsmetoder",
    "pozostałe metody płatności",
    "inne płatności z użyciem alternatywnych form płatności",
    "wszystkie inne alternatywne formy płatności",
    "άλλες εναλλακτικές μέθοδοι πληρωμής",
    "εναλλακτικές μέθοδοι πληρωμής",
    "övriga alternativa betalningsmetoder",
    "muut vaihtoehtoiset maksutavat",
    "más alternatív fizetési módok",
    "outros métodos de pagamento alternativos",
    "alte metode alternative de plată",
    "ostatné alternatívne spôsoby platby",
    " Ostali alternativni načini plačila",
    "alternatív fizetési módok",
    "alternative betalingsmåter",
    "alternative betalingsmetoder",
    "alternative betalingsmåder",
    "alternative betalningsmetoder",
    "alternative maksutavat",
    "alternativna sredstva plaćanja",
    "alternativni načini plaćanja",
    "alternativne metode plaćanja",
    "alternatívne spôsoby platby",
    "alternativní způsoby platby",
    "alternativní platební metody",
    "alternativne metody płatności",
    "alternatyvūs mokėjimo būdai",
    "alternatīvie maksājumi",
    "alternatīvie maksājumu veidi",
    "alternatívne platobné metódy",
    "alternativne metode plačila",
    "alternativne plačilne metode",
    "alternativni plačilni sistemi",
    "alternativni načini plačevanja",
    "alternativna plačilna sredstva",
    "alternativni plačilni mehanizmi",
    "alternativne metode plačevanja",
    "alternativne finančne storitve",
    "alternativne plačilne rešitve",
    "apm-transaktionsgebühren",
    "apm-transaktion",
    "apm-transaksjoner",
    "apm-transakcje",
    "apm-transakcija",
    "apm transactions",
    "apm transaction",
    "apm-transakciók",
    "apm-maksut",
    "apm-maksutapa",
    "apm-betalinger",
    "apm-betaling",
    "apm-betalning",
    "apm-betalningar",
    "apm-zahlungen",
    "apm-zahlung",
    "apm-maks",
    "apm",
    "abm",
    "vmt",
    "ofertas de pay later de paypal",
    "tarjeta de crédito",
    "tarjeta de débito",
    "buy buttons",
    "shopping cart buttons",
    "payment links",
    "wire transfer",
    "transfer to debit card",
    "cash a check",
    "standard credit",
    "debit card payments",
    "credit card payments",
    "standard debit",
}

_APM_HEADER_TOKENS: set[str] = {
    "alternative",
    "zahlungsmethode",
    "zahlungsmethoden",
    "payment",
    "payments",
    "method",
    "methods",
    "método",
    "métodos",
    "metodo",
    "metodi",
    "betaalmethode",
    "betaalmethoden",
    "moyen",
    "paiement",
    "pagamento",
    "pagamenti",
    "płatności",
    "maksutapa",
    "maksutavat",
    "platba",
    "mód",
    "módy",
    "apm",
    "apms",
    "abm",
    "vmt",
    "debito",
    "débito",
    "credito",
    "crédito",
    "debit",
    "credit",
    "card",
    "cards",
    "standard",
}

_THAI_TOKENS = {
    "thai",
    "thailand",
    "thailändisch",
    "thailändische",
    "thailändsk",
    "thailandsk",
    "thaimaan",
    "thaimaa",
    "thaiföldi",
    "thaïlandaise",
    "tailandesa",
    "tailandese",
    "tailandés",
    "tajlandzkiej",
    "thajsku",
    "thajska",
    "thajském",
    "thajskom",
    "tailandia",
    "tailândia",
    "thailande",
    "thaïlande",
}

_LATVIAN_TOKENS = {
    "latvian",
    "lettisch",
    "lettische",
    "latvijas",
    "latvijska",
    "läti",
    "lettországi",
    "letonska",
    "letonské",
    "letonskom",
    "letonia",
    "letonie",
    "letonië",
    "lettland",
    "letland",
}

_LITHUANIAN_TOKENS = {
    "lithuanian",
    "litauisch",
    "litauische",
    "liettualainen",
    "lietuvos",
    "litván",
    "litewska",
    "litewskim",
    "lie",
    "tuvos",
    "lituania",
    "lituanie",
    "litouwen",
    "litauen",
}

_ESTONIAN_TOKENS = {
    "estonian",
    "estnische",
    "estnisk",
    "estniska",
    "estlandsk",
    "esztorszagi",
    "esti",
    "estonia",
    "estonsku",
    "estónsku",
    "estnischen",
}

_BANK_TOKENS = {
    "bank",
    "banküberweisung",
    "bankuberweisung",
    "banktransfer",
    "bankoverførsel",
    "bankoverschrijving",
    "bankovní",
    "bankový",
    "banki",
    "átutalás",
    "virement",
    "bonifico",
    "transferencia",
    "transferência",
    "bancaire",
    "bancaria",
    "banco",
    "bancos",
    "banks",
    "banköverföring",
    "verkkopankki",
    "verkkopankkisiirto",
    "pankki",
    "siirto",
    "überweisung",
    "uberweisung",
    "transfer",
    "transfert",
    "overschrijving",
    "overførsel",
    "prevod",
    "przelew",
    "platba",
    "bankkonto",
    "bankkonten",
    "account",
}

_ONLINE_TOKENS = {
    "online",
    "on-line",
    "on",
    "line",
    "ligne",
    "línea",
    "elektronikus",
    "elektronische",
    "elektronisch",
    "eletrônico",
    "electronico",
    "elettronico",
    "internet",
    "verkkopankki",
}

_APM_METHOD_MATCHERS: list[tuple[str, list[set[str]], set[str]]] = [
    ("thai_online_bank_transfer", [_THAI_TOKENS, _ONLINE_TOKENS, _BANK_TOKENS], set()),
    ("latvian_online_bank_transfer", [_LATVIAN_TOKENS, _ONLINE_TOKENS, _BANK_TOKENS], set()),
    ("lithuanian_online_bank_transfer", [_LITHUANIAN_TOKENS, _ONLINE_TOKENS, _BANK_TOKENS], set()),
    ("estonian_online_bank_transfer", [_ESTONIAN_TOKENS, _BANK_TOKENS], set()),
    (
        "online_bank_transfer",
        [_ONLINE_TOKENS, _BANK_TOKENS],
        _THAI_TOKENS | _LATVIAN_TOKENS | _LITHUANIAN_TOKENS | _ESTONIAN_TOKENS,
    ),
    ("skrill", [{"skrill"}], set()),
    ("ovo_premium", [{"ovopremium", "ovo", "ovos"}], set()),
    ("gopay", [{"gopay", "go", "gopa"}], set()),
    ("blik_pay_later", [{"blikpaylater", "blik"}], set()),
    ("kredivo", [{"kredivo"}], set()),
    ("floa_pay", [{"floapay", "floa"}], set()),
    ("scalapay", [{"scalapay"}], set()),
    ("naver_pay", [{"naverpay", "naver"}], set()),
    ("picpay", [{"picpay"}], set()),
    ("nupay", [{"nupay"}], set()),
    ("true_money", [{"truemoney", "true"}], set()),
    ("airtel", [{"airtel"}], set()),
    ("pago_efectivo", [{"pagoefectivo", "pago"}], set()),
    ("mercado_pago", [{"mercadopago", "mercado"}], set()),
    ("pesa", [{"pesa", "mpesa"}], set()),
    ("shopee_pay", [{"shopeepay", "shopee"}], set()),
    ("twint", [{"twint"}], set()),
    ("doku_wallet", [{"dokuwallet", "doku"}], set()),
    ("linkaja", [{"linkaja"}], set()),
    ("jenius_pay", [{"jeniuspay"}], set()),
    ("paysera", [{"paysera"}], set()),
    ("dragonpay", [{"dragonpay"}], set()),
    ("codi", [{"codi"}], set()),
    ("halopesa", [{"halopesa"}], set()),
    ("mixx_by_yas", [{"mixxbyyas"}], set()),
    ("payattitude", [{"payattitude"}], set()),
    ("pesalink", [{"pesalink"}], set()),
    ("promptpay_qr", [{"promptpayqr"}], set()),
    ("pse", [{"pse"}], set()),
    ("bre_b", [{"breb"}], set()),
    ("nibss_bank_transfer", [{"nibbs", "nigerian", "nibss"}], set()),
    ("nequi", [{"nequi"}], set()),
    ("vietqr", [{"vietqr"}], set()),
    ("coins", [{"coins"}], set()),
    ("paysafecard", [{"paysafecard"}], set()),
    ("oxxopay", [{"oxxopay"}], set()),
    ("klarna", [{"klarna"}], set()),
    ("venmo", [{"venmo"}], set()),
    ("fiuu_cash", [{"fiuucash"}], set()),
    ("opay", [{"opay"}], set()),
    ("apple_pay", [{"applepay"}], set()),
    ("wire_transfer", [{"wire"}, {"transfer"}], set()),
    ("spei", [{"spei"}], set()),
    ("swish", [{"swish"}], set()),
    ("dimo", [{"dimo"}], set()),
]

_APM_VARIANTS: list[tuple[tuple[str, ...], str]] = [
    (
        (
            "pay link",
            "pay links",
            "payment link",
            "payment links",
            "payment links and buttons",
            "buy buttons",
            "shopping cart buttons",
            "zahlungslink",
            "liens de paiement",
        ),
        "payment_links",
    ),
    (("cash a check", "cheque", "check"), "cash_a_check"),
    (("wire transfer", "virement", "transferencia bancaria"), "wire_transfer"),
    (("spendback", "remboursement"), "spendback_transfer"),
    (("debit card", "carte de débit", "tarjeta de débito"), "debit_card_transfer"),
    (("bank transfer", "domestic bank transfer", "virement bancaire"), "bank_transfer"),
    (("third-party digital wallet", "third party digital wallet", "third-party wallet"), "third_party_wallet"),
    (("foreign exchange", "fx spread", "currency conversion"), "fx_service"),
]

_ADVANCED_CARD_VARIANTS: list[tuple[tuple[str, ...], str]] = [
    (
        (
            "eterminal",
            "terminal",
            "point of sale",
            "card present",
            "pagamenti telefonici",
            "telefonici",
            "pago por teléfono",
            "pagos por teléfono",
        ),
        "eterminal",
    ),
    (("standard credit", "carte standard", "tarjeta de crédito y débito"), "standard_card"),
    (("american express", "amex", "carte american express"), "american_express"),
    (
        (
            "advanced credit",
            "advanced debit",
            "carte bancaire avancés",
            "carte bancaire avancée",
            "cartes bancaires avancées",
            "pagamenti avanzati con carta",
            "avancerade betalningar med betalkort",
            "avancerat kredit- och betalkort",
        ),
        "advanced_card",
    ),
    (("payments advanced", "advanced payments", "payment advanced"), "payments_advanced"),
    (
        (
            "payments pro",
            "payment pro",
            "solution hébergée",
            "solution hébergée paypal",
            "hosted solution",
            "paypal pro",
            "pagamenti con paypal pro",
        ),
        "payments_pro",
    ),
    (("ach", "automated clearing", "addebito diretto", "sepa", "direktdebitering"), "ach"),
    (("additional risk", "risk factors", "risk factor", "chargeback protection", "fraud protection"), "risk_factors"),
    (("failure to implement", "express checkout", "checkout requis"), "express_checkout"),
    (("foreign exchange", "currency conversion", "devise", "fx as a service"), "fx_service"),
    (
        (
            "regroup",
            "flat rate",
            "forfait",
            "regroupée",
            "blended",
            "blandad prissättning",
            "piano tariffario misto",
            "combinada",
            "combinado",
            "tarifa combinada",
            "gecombineerde",
            "gecombineerd tarief",
            "kombinovanými sazbami",
            "kombinovanými sadzbami",
        ),
        "flat_rate",
    ),
    (("interchange plus plus", "interchange++"), "interchange_plus_plus"),
    (("interchange plus", "interchange+", "piano tariffario interchange plus"), "interchange_plus"),
]

_QR_BELOW_THRESHOLD: tuple[tuple[tuple[str, ...], str], ...] = (
    (
        (
            "unter",
            "under",
            "below",
            "less than",
            "<",
            "bis zu",
            "up to",
            "jusqu'à",
            "inférieure",
            "inférieures",
            "inferior",
            "inferiores",
            "inferiori",
            "pari o inferiori",
            "a méně",
            "og derunder",
            "derunder",
            "og under",
            "under",
            "a menej",
            "i mniej",
            "lub mniej",
            "co najwyżej",
            "o menos",
            "o meno",
            "o mniej",
            "no máximo",
            "até",
            "al massimo",
            "fino a",
            "tai vähemmän",
            "vähemmän",
            "en minder",
            "minder",
            "eller mindre",
            "höchstens",
            "legfeljebb",
            "kevesebb",
            "hasta",
            "nejvýše",
            "nebo méně",
            "najviac",
            "alebo menej",
            "nižšej",
            "a nižšej",
            "ή λιγότερα",
            "λιγότερα",
            "και κάτω",
            "och lägre",
            "及以下",
            "或以下",
        ),
        "below_threshold",
    ),
)

_QR_ABOVE_THRESHOLD: tuple[tuple[tuple[str, ...], str], ...] = (
    (
        (
            "over",
            "above",
            "greater than",
            ">",
            "mindestens",
            "at least",
            "à partir de",
            "au moins",
            "supérieure",
            "supérieures",
            "superior",
            "superiores",
            "superiori",
            "pari o superiori",
            "a více",
            "og derover",
            "derover",
            "og over",
            "over",
            "a viac",
            "i więcej",
            "lub więcej",
            "co najmniej",
            "o más",
            "o mas",
            "o più",
            "ou mais",
            "no mínimo",
            "pelo menos",
            "almeno",
            "più di",
            "tai enemmän",
            "enemmän",
            "en meer",
            "meer",
            "eller mer",
            "eller fler",
            "legalább",
            "több mint",
            "meghaladó",
            "a partir de",
            "desde",
            "nejméně",
            "nebo více",
            "najmenej",
            "alebo viac",
            "vyššej",
            "a vyššej",
            "ή περισσότερα",
            "περισσότερα",
            "και πάνω",
            "och högre",
            "及以上",
            "或以上",
        ),
        "above_threshold",
    ),
)

_MICROPAYMENT_VARIANTS: tuple[tuple[tuple[str, ...], str], ...] = (
    (("mass payment", "mass payments"), "mass_payments"),
    (("digital", "digitala", "digitale", "dijital"), "digital_goods"),
)

_PAYPAL_CHECKOUT_VARIANTS: tuple[tuple[tuple[str, ...], str], ...] = (
    (("crypto", "bitcoin", "cryptocurrency", "krypto", "cryptomonnaie", "criptomoneda"), "crypto"),
)

_OTHER_COMMERCIAL_VARIANTS: tuple[tuple[tuple[str, ...], str], ...] = (
    (("campaign", "store cash", "campagne"), "campaign_fee"),
    (("pyusd",), "pyusd"),
    (("ach", "pay by bank", "virement bancaire"), "ach"),
    (
        (
            "card funded",
            "approvisionné par carte",
            "financiada",
            "financiado por cartão",
            "card-funded",
            "kortfinansierad",
            "kortilla rahoitettu",
            "kártyás kifizetések",
            "pagamento con carta",
            "kaartbetaling",
            "betaald met kaart",
            "kartou hrazená",
            "platba kartou",
            "płatność kartą",
            "płatności kartą",
        ),
        "card_funded",
    ),
)

_POS_VARIANTS: tuple[tuple[tuple[str, ...], str], ...] = (
    (("qr code", "qr-code", "qr-kode", "qr kod"), "qr_code"),
    (
        (
            "manual",
            "manuelle",
            "manuale",
            "manual entry",
            "saisie manuelle",
            "saisie",
            "manuell inmatning",
            "manuel indtastning",
            "manuelle eingabe",
            "handmatig",
            "handmatig ingevoerd",
        ),
        "manual_entry",
    ),
    (
        (
            "card present",
            "present",
            "präsent",
            "présente",
            "presente",
            "transactions par carte",
            "transaktionen mit präsenter karte",
            "aktuella korttransaktioner",
            "korttransaktioner",
            "kortforevisning",
            "carta presente",
            "kaart aanwezig",
            "tilstedeværende kort",
        ),
        "card_present",
    ),
    (
        (
            "payment link",
            "zahlungslink",
            "zahlungslinks",
            "liens de paiement",
            "payment links",
            "betalningslänkar",
            "betalingslinks",
            "link di pagamento",
            "links de pagamento",
            "betaallinks",
            "betalingslink",
            "betalingslenker",
        ),
        "payment_links",
    ),
)

_DONATIONS_VARIANTS: tuple[tuple[tuple[str, ...], str], ...] = (
    (
        (
            "aufgeführte",
            "aufgelistet",
            "listed",
            "listed campaigns",
            "in elenco",
            "presenti in elenco",
            "indicadas",
            "indicada",
            "indicados",
            "indicado",
            "indiquées",
            "listées",
            "listado",
            "listados",
            "listada",
            "listadas",
        ),
        "campaign_listed",
    ),
    (
        (
            "nicht aufgeführte",
            "unlisted",
            "non listée",
            "non listados",
            "non listate",
        ),
        "campaign_unlisted",
    ),
    (
        (
            "campaign",
            "aktion",
            "collect",
            "campagne",
            "collecte",
            "cause",
            "dons collectifs",
            "fundraiser",
            "fundraisers",
            "fundraising",
            "recaudación",
            "recaudacion",
            "recaudación de fondos",
            "raccolta",
            "raccolta fondi",
            "collecte de fonds",
            "fundraising-kampagne",
        ),
        "campaign",
    ),
    (("button", "bouton", "botón", "pulsante", "knop"), "button"),
)

_APM_VARIANT_ONLY_VARIANTS: frozenset[str] = frozenset(
    {
        "payment_links",
        "cash_a_check",
        "wire_transfer",
        "spendback_transfer",
        "debit_card_transfer",
        "bank_transfer",
        "third_party_wallet",
        "fx_service",
    }
)

_INVOICE_VARIANTS: tuple[tuple[tuple[str, ...], str], ...] = (
    (("rückzahlung", "repayment", "remboursement", "reembolso", "rimborso", "refund", "refund"), "repayment"),
)

_NONPROFIT_VARIANTS: tuple[tuple[tuple[str, ...], str], ...] = (
    (("qr-code", "qr code", "qr-code-transaktionen", "qr-code-transaktion", "qr-code-zahlungen"), "qr_code"),
)

_PAY_LATER_VARIANTS: tuple[tuple[tuple[str, ...], str], ...] = (
    (("payment link", "payment links", "zahlungslink", "liens de paiement"), "payment_links"),
)

_QR_VARIANTS: tuple[tuple[tuple[str, ...], str], ...] = _QR_BELOW_THRESHOLD + _QR_ABOVE_THRESHOLD

_DISPUTE_VARIANTS: tuple[tuple[tuple[str, ...], str], ...] = (
    (("high volume", "high-volume", "hochvolumen", "grand volume", "alto volumen", "høj volumen"), "high_volume"),
    (("standard", "standart", "standard dispute"), "standard"),
)

_WITHDRAWAL_VARIANTS: tuple[tuple[tuple[str, ...], str], ...] = (
    (("ach", "automated clearing", "automated clearing house"), "ach"),
    (("wire transfer", "virement", "transferencia bancaria", "bank transfer"), "wire_transfer"),
    (("bank return", "return on withdrawal", "return on transfer", "returned"), "bank_return"),
    (("instant transfer", "instant bank transfer"), "instant_transfer"),
    (("bank account", "to a bank account"), "bank_account"),
    (("business debit", "business debit card", "bargeld", "geldautomat", "atm"), "business_debit_atm"),
    (("cards", "card"), "cards"),
    (("paypal payouts", "payouts"), "payouts"),
)

_SEPA_DIRECT_DEBIT_VARIANTS: tuple[tuple[tuple[str, ...], str], ...] = (
    # Instant must be checked before standard because "Standardabrechnung" can
    # appear inside a cell that also mentions the instant option.
    (
        (
            "instant",
            "sofort",
            "sofortige",
            "sofortabrechnung",
            "instant settlement",
            "istantanea",
            "istantaneo",
        ),
        "instant_settlement",
    ),
    (("standard", "standardabrechnung", "standard settlement"), "standard_settlement"),
)

_FRAUD_PROTECTION_VARIANTS: tuple[tuple[tuple[str, ...], str], ...] = (
    (("advanced", "professionelles tool", "professionelles"), "advanced"),
)

_RECORDS_REQUEST_VARIANTS: tuple[tuple[tuple[str, ...], str], ...] = ((("standard",), "standard"),)

_CARD_VERIFICATION_VARIANTS: tuple[tuple[tuple[str, ...], str], ...] = ((("standard",), "standard"),)

_VARIANT_RULES_BY_PRODUCT: dict[str, tuple[tuple[tuple[str, ...], str], ...]] = {
    "advanced_card_payments": tuple(_ADVANCED_CARD_VARIANTS),
    "alternative_payment_methods": tuple(_APM_VARIANTS),
    "qr_code_payments": _QR_VARIANTS,
    "disputes": _DISPUTE_VARIANTS,
    "withdrawals": _WITHDRAWAL_VARIANTS,
    "sepa_direct_debit": _SEPA_DIRECT_DEBIT_VARIANTS,
    "fraud_protection": _FRAUD_PROTECTION_VARIANTS,
    "records_request": _RECORDS_REQUEST_VARIANTS,
    "card_verification": _CARD_VERIFICATION_VARIANTS,
}

_BASE_VARIANTS_BY_PRODUCT: dict[str, frozenset[str]] = {
    "advanced_card_payments": frozenset({v for _, v in _ADVANCED_CARD_VARIANTS} | {"donations"}),
    "alternative_payment_methods": frozenset(
        {
            "default",
            "special",
            "bank_transfer",
            "debit_card_transfer",
            "spendback_transfer",
            "cash_a_check",
            "wire_transfer",
        }
    ),
    "other_commercial": frozenset({"standard", "campaign_fee", "pyusd", "ach", "card_funded"}),
    "paypal_checkout": frozenset({"standard", "venmo"}),
    "invoice_pay_later": frozenset({"standard", "payment_links"}),
    "qr_code_payments": frozenset({"standard"}),
    "micropayments": frozenset({"standard", "digital_goods", "mass_payments"}),
    "disputes": frozenset({"standard"}),
    "withdrawals": frozenset({"withdrawal", "bank_account", "cards"}),
    "sepa_direct_debit": frozenset({"standard_settlement"}),
    "fraud_protection": frozenset({"advanced"}),
    "records_request": frozenset({"standard"}),
    "card_verification": frozenset({"standard"}),
}

_ADVANCED_CARD_SCHEDULE_KEYWORDS: tuple[str, ...] = (
    "advanced credit and debit card payments",
    "advanced card",
    "payments advanced",
    "payments pro",
    "virtual terminal",
    "eterminal",
    "e-terminal",
    "paypal intégral évolution",
    "intégral évolution",
    "interchange plus plus",
    "interchange plus",
    "paypal card payment services",
)

_SCHEDULE_NAME_FROM_TABLE_MAPPING = {
    "goods_and_services": (
        "geld für waren und dienstleistungen",
        "waren und dienstleistungen",
        "goods and services",
        "varer og tjenesteydelser",
        "varer og tjenester",
        "bienes y servicios",
        "beni e servizi",
        "goederen en diensten",
        "produkter och tjänster",
        "produkter og tjenester",
    ),
    "donations": (
        "spende",
        "donation",
        "donationer",
        "donations",
        "donaties",
        "donativos",
        "donativas",
        "doações",
        "donazioni",
        "lahjoitukset",
        "darowizn",
        "príspevkov",
        "príspevky",
        "adományok",
        "δωρεές",
        "δωρεες",
        "donatii",
        "дарения",
        "donacije",
        "donacijo",
        "příspěvky",
        "příspěvků",
    ),
    "nonprofit": (
        "gemeinnützig",
        "nonprofit",
        "non-profit",
        "velgørende",
        "charity",
        "charitable",
        "charitat",
        "caridad",
        "caridade",
        "caritative",
        "organizaciones sin fines de lucro",
        "organizaciones benéficas",
        "organización benéfica",
        "benéfica",
        "benéficas",
        "organizzazioni senza scopo di lucro",
        "organisasjoner",
        "organizacja non-profit",
        "organizacje charytatywne",
        "charitatívnych",
        "charitativních",
        "charitativní",
        "jótékonysági",
        "välgörenhetsorganisationer",
        "välgörenhet",
        "φιλανθρωπικές",
        "φιλανθρωπικά",
        "φιλανθρωπικού",
        "instituições de solidariedade",
        "instituição de caridade",
        "institución de solidaridad",
        "entidades sin ánimo de lucro",
        "associazioni di volontariato",
        "enti benefici",
        "ente benefico",
        "a favore di enti benefici",
        "liefdadigheid",
    ),
    "micropayments": (
        "mikrozahlung",
        "micropayment",
        "mikrobetaling",
        "mikrobetalinger",
        "microbetaling",
        "microbetalingen",
        "mikromaksu",
        "mikromaksut",
        "mikropłatność",
        "mikropłatności",
        "micropagos",
        "micropaiement",
        "micropaiements",
        "micropagamentos",
        "mikrobetalning",
        "mikrobetalningar",
        "mikroplatby",
        "mikroπληρωμές",
        "μικροπληρωμές",
        "μικροπληρωμες",
        "mikrotransakciók",
        "mikrotransakcije",
        "mikrokifizetés",
        "mikrokifizetések",
        "micropagamenti",
        "小額付款",
        "小额付款",
        "小額支付",
        "小额支付",
    ),
    "alternative_payment_methods": (
        "alternative zahlungsmethode",
        "alternative payment",
        "apm",
        "alternativ betalingsmetode",
        "alternative betalingsmetode",
        "alternative betaalmethode",
        "métodos de pago alternativos",
        "metodi di pagamento alternativi",
        "metodo di pagamento alternativo",
        "andere betaalmethode",
        "autre moyen de paiement",
        "autre mode de paiement",
        "alternatív fizetési",
        "alternatívny spôsob platby",
        "alternativní způsob platby",
        "alternatywna forma płatności",
        "alternativ betalningsmetod",
        "alternativ betalingsmåte",
        "vaihtoehtoinen maksutapa",
        "vmt",
        "abm",
        "εναλλακτικός τρόπος πληρωμής",
        "εναλλακτικος τροπος πληρωμης",
        "συναλλαγές με εμπ",
        "συναλλαγες με εμπ",
    ),
    "online_card_payments": (
        "online-kartenzahlungen",
        "online card",
        "online card payments",
        "online-kortbetaling",
        "online kort",
        "online kortbetalingstjenester",
        "kortbetalingstjenester",
        "kortbetalningstjänster",
        "kortbetalning",
        "tarjetas de crédito y débito",
        "kredit- och debitkort",
        "kredit- og betalingskort",
        "credit and debit card",
        "servizi di pagamento con carta",
        "services de paiement par carte",
        "serviços de pagamento com cartão",
        "servicios de pago con tarjeta",
        "online platby kartou",
        "online kártyás",
        "online betaalservices",
        "transacties ontvangen via online betaalservices",
        "pago por internet",
        "servicios de pago por internet",
        "płatności online kartą",
        "usług płatności online kartą",
        "verkkokorttimaksupalvelut",
        "verkkokorttimaksu",
        "ηλεκτρονικές πληρωμές με κάρτα",
        "ηλεκτρονικες πληρωμες με καρτα",
        "υπηρεσιών paypal για ηλεκτρονικές",
        "υπηρεσιων paypal για ηλεκτρονικες",
    ),
    "pos_transactions": (
        "point of sale",
        "präsenter karte",
        "kortforevisning",
        "card present",
        "ponto de venda",
        "punto de venta",
        "punto vendita",
        "punkty sprzedaży",
    ),
    "qr_code_payments": (
        "qr",
        "qr-code",
        "qr code",
        "qr code payments",
        "qr-code-transaktionen",
        "qr-code-transaktion",
        "qr-code-zahlungen",
        "qr-code-zahlung",
        "qr-code-betalinger",
        "qr kode",
        "qr-kode",
        "qr kode-betalinger",
        "qr-kode-betalinger",
        "kódů qr",
        "qr kódů",
        "kódy qr",
        "qr kódy",
        "código qr",
        "códigos qr",
    ),
    "invoice_pay_later": (
        "invoicing",
        "invoicing transaction",
        "invoice",
        "rechnung",
        "rechnungen",
        "facture",
        "facturas",
        "fattura",
        "fatture",
        "factuur",
        "faktura",
        "faktury",
        "faktur",
        "számla",
        "fakturor",
    ),
    "advanced_card_payments": (
        "advanced credit and debit card payments",
        "advanced credit",
        "advanced debit",
        "payments advanced",
        "payments pro",
        "pasarela integral",
        "virtual terminal",
        "eterminal",
        "e-terminal",
        "paypal intégral évolution",
        "intégral évolution",
        "pago por teléfono",
        "pagos por teléfono",
        "pagamento telefonico",
        "pagamenti telefonici",
        "servizi telefonici",
        "telefónico",
        "telefónica",
        "telefonisch",
        "telefonische",
        "téléphonique",
        "téléphoniques",
        "telefonico",
        "telefonica",
        "paypal pro",
        "interchange plus plus",
        "interchange plus",
        "payPal card payment services",
        "card payment services",
        "erweiterte kredit- und debitkartenzahlungen",
        "zahlungen mit kredit- und debitkarten mit erweiterten funktionen",
        "kredit- und debitkarten mit erweiterten funktionen",
        "advanced card",
        "erweiterte kartenzahlung",
        "kredit- og betalingskort",
        "kredit- og debitkort",
        "kredit- och debitkort",
        "kreditkort",
        "credit and debit card",
        "servizi di pagamento con carta",
        "services de paiement par carte",
        "serviços de pagamento com cartão",
        "servicios de pago con tarjeta",
        "online platby kartou",
        "online kártyás",
        "verkkokorttimaksupalvelut",
        "verkkokorttimaksu",
        "ηλεκτρονικές πληρωμές με κάρτα",
        "ηλεκτρονικες πληρωμες με καρτα",
    ),
    "recipient_service": (
        "recipient service",
        "recipients of eea",
        "recipients of",
        "recipient of",
        "eea based",
        "empfänger",
        "empfängerinnen",
        "ontvanger",
        "destinatario",
        "destinataire",
        "grand-bretagne",
        "großbritannien",
        "united kingdom",
        "in großbritannien ansässig",
        "british recipient",
        "uk recipient",
        "příjemce",
        "příjemců",
        "příjemci",
        "příjemcům",
        "príjemca",
        "príjemcov",
        "príjemcom",
        "odběratel",
        "odběratele",
        "velké británii",
        "velká británie",
        "velká británia",
        "wielka brytania",
        "wielkiej brytanii",
        "regatul unit",
        "marea britanie",
        "wielkiej brytanii",
        "fogadó",
        "fogadó felek",
        "címzett",
        "egyesült királyság",
        "egyesült királyságban",
        "mottagare",
        "mottakere",
        "mottaker",
        "storbritannien",
        "storbritannia",
        "regno unito",
        "destinatari",
        "παραλήπτες",
        "παραλήπτης",
        "ηνωμένο βασίλειο",
        "ηνωμένου βασιλείου",
        "spojeného kráľovstva",
        "spojené kráľovstvo",
        "für empfänger",
        "für empfängerinnen",
        "aus großbritannien",
        "from the united kingdom",
        "united kingdom based",
        "united kingdom-based",
    ),
    "withdrawals": (
        "withdrawal",
        "withdrawals",
        "withdraw",
        "auszahlung",
        "auszahlungen",
        "payout",
        "payouts",
        "uttag",
        "uitoog",
        "wypłata",
        "retrait",
        "retiro",
        "ritiro",
        "bank transfer",
        "bank transfer withdrawal",
        "transfer to card",
        "transfer to a card",
        "μεταφορά σε κάρτα",
        "transfert sur carte",
        "transferencia a tarjeta",
        "trasferimento su carta",
        "überweisung auf karte",
        "przelew na kartę",
        "převod na kartu",
        "prevod na kartu",
        "transfer do karty",
        "kártyára történő átutalás",
        "transfer till kort",
        "overførsel til kort",
        "disbursement",
        "disbursements",
        "wire transfer",
        "wire transfer disbursement",
        "abbuchen",
        "guthaben von einem paypal-geschäftskonto abbuchen",
    ),
    "chargebacks": (
        "chargeback",
        "chargebacks",
        "rückbuchung",
        "rückbuchungen",
        "rückbuchungsgebühr",
        "contra reembolso",
        "chargeback fee",
        "chargeback fees",
    ),
    "refunds": (
        "refund",
        "refunds",
        "rückerstattung",
        "rückerstattungen",
        "erstattung",
        "erstattungen",
        "terugbetaling",
        "remboursement",
        "rimborso",
        "reembolso",
    ),
    "disputes": (
        "dispute",
        "disputes",
        "streit",
        "claim",
        "claims",
        "disputed",
        "klage",
        "beschwerde",
        "geschil",
        "litige",
        "controversia",
        "contestazione",
    ),
    "card_verification": (
        "card verification",
        "kartenverifizierung",
        "kartenbestätigung",
        "kreditkartenbestätigung",
        "credit card verification",
        "debit card verification",
        "3d secure",
        "verification",
        "verifizierung",
    ),
    "commercial": (
        "geschäftlichen transaktionen",
        "commercial transaction",
        "commercial",
        "erhvervsbetalinger",
        "erhverv",
        "business payments",
        "standardgebyr",
        "standardavgift",
        "standaardtarief",
        "tarifa estándar",
        "tarifa standard",
        "tarifa padrão",
        "tariffa standard",
        "tarification standard",
        "standard fee",
        "standard rate",
        "standardní sazba",
        "štandardná sadzba",
        "szokásos díja",
        "szokásos díj",
        "standardowa stawka",
        "standardtaxa",
        "standardsats",
        "standard taxa",
        "εμπορικές συναλλαγές",
        "εμπορικες συναλλαγες",
        "commerciale",
        "commerciële",
        "commerciale",
        "kommersielle",
        "kommercielle",
        "kommersiella",
        "komercyjne",
        "komerčních",
        "komerčných",
        "kereskedelmi",
        "comerciale",
        "obchodní transakce",
        "obchodné transakcie",
        "emporia",
    ),
}

_REGION_EXACT: dict[str, str] = {
    "eu": "EEA",
    "gb": "GB",
    "uk": "GB",
    "us": "US_CA",
    "eøs": "EEA",
    "ees": "EEA",
    "eea": "EEA",
    "eee": "EEA",
    "ehp": "EEA",
    "egt": "EEA",
    "eta": "EEA",
    "see": "EEA",
    "eer": "EEA",
    "εοχ": "EEA",
}

RegionPattern = str | tuple[str, ...]

_REGION_PATTERNS: tuple[tuple[str, tuple[RegionPattern, ...]], ...] = (
    ("EUROPE_II", ("europa ii",)),
    ("EUROPE_I", ("europa i",)),
    (
        "NORTHERN_EUROPE",
        ("nordeuropa", "northern europe", "nordic", "pohjois-eurooppa"),
    ),
    (
        "EEA",
        (
            "europäischer wirtschaftsraum",
            "ewr",
            "eea",
            "e.u",
            "eøs",
            "ees",
            "see",
            "eee",
            "ehp",
            "egt",
            "eta",
            "eer",
            "εοχ",
            "espace économique européen",
            "spazio economico europeo",
            "espacio económico europeo",
            "europæiske økonomiske samarbejdsområde",
            "europeisk økonomisk samarbeidsområde",
            "europeiska ekonomiska samarbetsområdet",
            "europese economische ruimte",
            "euroopan talousalue",
            "europski gospodarski prostor",
            "európai gazdasági térség",
        ),
    ),
    (
        "GB",
        (
            "vereinigtes königreich",
            "großbritannien",
            "storbritannien",
            "storbritannia",
            "united kingdom",
            "britain",
            "regno unito",
            "royaume-uni",
            "royaume uni",
            "verenigd koninkrijk",
            "iso-britannia",
            "Ηνωμένο Βασίλειο",
            "ηνωμενο βασιλειο",
            "britannien",
            "spojuené kráľovstvo",
            "spojené království",
            "egyesült királyság",
            "britannia",
        ),
    ),
    (
        "US_CA",
        (
            "usa",
            "united states",
            "u.s",
            "canada",
            "nordamerika",
            "états-unis",
            "etats-unis",
            "stati uniti",
            "estados unidos",
            "verenigde staten",
            "yhdysvallat",
            "ΗΠΑ",
            "ηπα",
        ),
    ),
    (
        "OTHER",
        (
            ("all", "other"),
            ("all", "andere"),
            ("tutti", "altri"),
            ("tous", "autres"),
            ("kaikki", "muut"),
            ("alle", "andere"),
            ("alle", "ander"),
            ("všechny", "ostatní"),
            ("všetky", "ostatné"),
            ("minden", "egyéb"),
            ("λοιπες",),
            ("rest",),
            ("restante",),
            ("andere",),
            ("sonstige",),
            ("welt",),
            ("andre", "markeder"),
            ("andre", "lande"),
            ("andere", "länder"),
            ("altri", "paesi"),
            ("altri", "mercati"),
            ("otros", "países"),
            ("otros", "mercados"),
            ("inni", "kraje"),
            ("pozostale",),
            ("pozostałe",),
            ("andre", "marknader"),
            ("alla", "andra", "marknader"),
            ("alle", "andere", "markten"),
            ("kaikki", "muut", "markkinat"),
            ("všechny", "ostatní", "trhy"),
            ("všetky", "ostatné", "trhy"),
            ("minden", "egyéb", "piac"),
            ("λοιπες", "αγορες"),
        ),
    ),
)

_REFERENCE_SCHEDULE_KEYWORDS: dict[str, tuple[str, ...]] = {
    "online_card_payments": (
        "online-kartenzahlungen",
        "online card payments",
        "erweiterte kredit- und debitkartenzahlungen",
        "advanced credit and debit card",
        "online card",
    ),
    "alternative_payment_methods": (
        "alternative zahlungsmethode",
        "alternative payment methods",
        "alternative payment",
        "apm",
    ),
    "goods_and_services": (
        "waren und dienstleistungen",
        "goods and services",
    ),
    "donations": (
        "spenden",
        "donation",
    ),
    "nonprofit": (
        "gemeinnützig",
        "nonprofit",
    ),
    "other_commercial": (
        "geschäftliche transaktionen",
        "commercial transactions",
        "commercial transaction fees",
        "comercial",
        "transacciones comerciales",
        "transações comerciais",
        "transazioni commerciali",
        "transactions commerciales",
    ),
}

_REFERENCE_SUFFIX_TO_PRODUCT: dict[str, str] = {
    "advanced": "advanced_card_payments",
}

_REFERENCE_PRODUCT_SUFFIX: dict[str, str] = {v: k for k, v in _REFERENCE_SUFFIX_TO_PRODUCT.items()}

_FIXED_FEE_SCHEDULE_FOR: dict[str, str | None] = {
    "paypal_checkout": "paypal_checkout",
    "goods_and_services": "goods_and_services",
    "online_card_payments": "online_card_payments",
    "advanced_card_payments": "advanced_card_payments",
    "other_commercial": "other_commercial",
    "guest_checkout": "guest_checkout",
    "invoice_pay_later": "invoice_pay_later",
    "pay_later_consumer": "pay_later_consumer",
    "qr_code_payments": "qr_code_payments",
    "donations": "donations",
    "nonprofit": "nonprofit",
    "micropayments": "micropayments",
    "alternative_payment_methods": "alternative_payment_methods",
    "pos_transactions": None,
    "chargebacks": "chargebacks",
    "refunds": "refunds",
    "disputes": "disputes",
    "card_verification": "card_verification",
    "currency_conversion": None,
    "withdrawals": "withdrawals",
}

_FIXED_FEE_INHERITANCE: dict[str, str] = {
    "paypal_checkout": "commercial",
    "other_commercial": "commercial",
    "guest_checkout": "commercial",
    "invoice_pay_later": "commercial",
    "pay_later_consumer": "commercial",
    "advanced_card_payments": "online_card_payments",
}

_FIXED_FEE_SCHEDULE_FALLBACK: dict[str, tuple[str, ...]] = {
    "paypal_checkout": ("commercial",),
    "other_commercial": ("commercial",),
    "guest_checkout": ("commercial",),
    "invoice_pay_later": ("commercial",),
    "pay_later_consumer": ("commercial",),
    "advanced_card_payments": ("online_card_payments",),
}

_INTERNATIONAL_SURCHARGE_SCHEDULE_FOR: dict[str, str | None] = {
    "paypal_checkout": "paypal_checkout",
    "goods_and_services": "goods_and_services",
    "online_card_payments": "online_card_payments",
    "advanced_card_payments": "advanced_card_payments",
    "other_commercial": "other_commercial",
    "guest_checkout": "guest_checkout",
    "invoice_pay_later": "invoice_pay_later",
    "pay_later_consumer": "pay_later_consumer",
    "qr_code_payments": None,
    "donations": "donations",
    "nonprofit": "nonprofit",
    "micropayments": None,
    "alternative_payment_methods": None,
    "pos_transactions": None,
    "chargebacks": None,
    "refunds": None,
    "disputes": None,
    "card_verification": None,
    "currency_conversion": None,
    "withdrawals": None,
}

_INTERNATIONAL_SURCHARGE_INHERITANCE: dict[str, str] = {
    "paypal_checkout": "commercial",
    "other_commercial": "commercial",
    "guest_checkout": "commercial",
    "invoice_pay_later": "commercial",
    "pay_later_consumer": "commercial",
    "advanced_card_payments": "commercial",
}

_INTERNATIONAL_SURCHARGE_SCHEDULE_FALLBACK: dict[str, tuple[str, ...]] = {
    "paypal_checkout": ("commercial",),
    "other_commercial": ("commercial",),
    "guest_checkout": ("commercial",),
    "invoice_pay_later": ("commercial",),
    "pay_later_consumer": ("commercial",),
    "advanced_card_payments": ("commercial",),
}

_MAXIMUM_FEE_SCHEDULE_FALLBACK: dict[str, tuple[str, ...]] = {
    "payouts_us": ("payouts_international",),
}

_DIRECT_FIXED_FEE_SCHEDULE_PRODUCTS: dict[str, str] = {
    "chargebacks": "chargebacks",
    "refunds": "refunds",
    "disputes": "disputes",
    "card_verification": "card_verification",
    "withdrawals": "withdrawals",
}

_STATUS_DEFECT_DIAGNOSTICS: set[str] = {
    "missing_required_schedule",
    "conflicting_schedule_entry",
    "conflicting_rule_identity",
    "unresolved_reference",
    "unresolved_nested_reference",
    "ambiguous_identity",
    "unsupported_fee_shape",
    "ambiguous_reference",
    "unknown_apm_method",
    "inappropriate_inheritance",
}
